#!/usr/bin/python
#   Copyright 2008 Red Hat, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
import getopt
import os
import sys
import re
import signal
from qmf.console import Session
from remoteconfig.config_utils import *


def exit_signal_handler(signum, frame):
   sys.exit(0)


def print_help(name):
   print 'usage: %s [-h|--help] -b|--broker <broker> [-p|--port <port>] action [-f|--features feature[,feature,...]] [-p|--params param[=1],param2[=string],...] [-n|--nodes hostname,hostname] [-g|--groups group[,group]] [-s|--subsys subsystem[,subsystem]]' % os.path.basename(name)
   print '  <broker> - The ip/hostname of the broker used by the configuration store'
   print '  <port> - The port of the broker used by the configuration store'
   print '  -h - Print help'
   print '\naction:'
   print '  -a|--add    - Add the target(s) to the store'
   print '  -d|--delete - Remove the target(s) from the store'
   print '  -e|--edit   - Edit the target(s) in the store'
   print '  -l|--list   - List configuration store information.  If provided'
   print '                without any targets, lists all items in the store.'
   print '                If a target is provided, print the information'
   print '                for the provided targets'


def process_comma_sep_list(list):
   params = {}
   if list != '':
      for pair in list.split(','):
         split = pair.split('=')
         if len(split) > 1:
            params[split[0].strip()] = split[1].strip()
         else:
            params[split[0].strip()] = True
   return params


def add_feature(sess, store, name):
   # Add the feature to the store
   print 'Adding feature "%s"' % name
   result = store.AddFeature(name)
   if result.status != 0:
      print 'Error: Failed to add feature "%s" (%d, %s)' % (name, result.status, result.txt)
      return(None)
   else:
      obj = sess.getObjects(_objectId=result.outArgs['obj'])
      if obj != []:
         return(obj[0])
      else:
         return(None)


def modify_feature(obj, name, action):
   # Get the information needed for the feature
   answer = 'y'
   print 'Modifying feature "%s"' % name
   if action == 'edit':
      answer = raw_input('Modify the parameters included in feature "%s" [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetParams()
         if result.status != 0:
            print 'Error: Failed to retrieve current parameter list for feature "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            print 'Current configured parameters:'
            val = result.outArgs['params']
            list = ''
            for key in val.keys():
               list += '%s=%s,' % (key, val[key])
            print list[:-1]
   if answer.lower() == 'y':
      input = raw_input('List of parameters (param=value,param=value,etc): ')
      list = {}
      for pair in input.split(','):
         param = pair.split('=')
         if len(param) != 2:
            list[param[0].strip()] = False
         else:
            list[param[0].strip()] = param[1].strip()
      result = obj.ModifyParams('replace', list, {})
      if result.status != 0:
          print 'Error: Failed to modify parameters of feature "%s" (%d, %s)' % (name, result.status, result.txt)

   if action == 'edit':
      answer = raw_input('Modify the features included in feature "%s" [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetFeatures()
         if result.status != 0:
            print 'Error: Failed to retrieve current feature list for feature "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            print 'Current configured features:'
            val = result.outArgs['features']
            list = ''
            for key in val.keys():
               list += '%s=%s,' % (val[key], key)
            print list[:-1]
   if answer.lower() == 'y':
      valid_input = False
      while valid_input == False:
         input = raw_input('Feature names this feature will include (feature=priority,feature=priority,etc): ')
         list = {}
         valid_input = True
         for pair in input.split(','):
            param = pair.split('=')
            if len(param) < 2:
               print 'Error: Invalid input.  "%s" must be assigned a priority' % param[0].strip()
               valid_input = False
               break
            elif param[1] in list:
               print 'Error: Two features have the same priority of "%s"' % param[1].strip()
               valid_input = False
               break
            else:
               list[param[1].strip()] = param[0].strip()
      result = obj.ModifyFeatures('replace', list, {})
      if result.status != 0:
         print 'Error: Failed to modify included features for feature "%s" (%d, %s)' % (name, result.status, result.txt)

   if action == 'edit':
      answer = raw_input('Modify the features that conflict with feature "%s" [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetConflicts()
         if result.status != 0:
            print 'Error: Failed to retrieve current list of conflicts for feature "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            print 'Current configured feature conflicts:'
            val = result.outArgs['conflicts']
            list = ''
            for key in val.keys():
               list += '%s,' % key
            print list[:-1]
   if answer.lower() == 'y':
      input = raw_input('Comma separated list of feature names this feature conflicts with: ')
      list = process_comma_sep_list(input)
      result = obj.ModifyConflicts('replace', list, {})
      if result.status != 0:
         print 'Error: Failed to modify conflicts of feature "%s" (%d, %s)' % (name, result.status, result.txt)

   if action == 'edit':
      answer = raw_input('Modify the features that depend on feature "%s" [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetDepends()
         if result.status != 0:
            print 'Error: Failed to retrieve current list of dependencies for feature "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            print 'Current configured feature dependencies:'
            val = result.outArgs['depends']
            list = ''
            for key in val.keys():
               list += '%s=%s,' % (key, val[key])
            print list[:-1]
   if answer.lower() == 'y':
      valid_input = False
      while valid_input == False:
         input = raw_input('Feature names this feature depends on (feature=priority,feature=priority,etc): ')
         list = {}
         valid_input = True
         for pair in input.split(','):
            param = pair.split('=')
            if len(param) < 2:
               print 'Error: Invalid input.  "%s" must be assigned a priority' % param[0].strip()
               valid_input = False
               break
            elif param[1] in list:
               print 'Error: Two features have the same priority of "%s"' % param[1].strip()
               valid_input = False
               break
            else:
               list[param[1].strip()] = param[0].strip()
      result = obj.ModifyDepends('replace', list, {})
      if result.status != 0:
         print 'Error: Failed to modify depends of feature "%s" (%d, %s)' % (name, result.status, result.txt)

   if action == 'edit':
      answer = raw_input('Modify the list of subsystems that feature "%s" uses [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetSubsys()
         if result.status != 0:
            print 'Error: Failed to retrieve current list of subsystems for feature "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            print 'Current configured subsystems:'
            val = result.outArgs['subsystems']
            list = ''
            for key in val.keys():
               list += '%s,' % key
            print list[:-1]
   if answer.lower() == 'y':
      input = raw_input('Comma separated list of subsystems this feature uses: ')
      list = process_comma_sep_list(input)
      result = obj.ModifySubsys('replace', list)
      if result.status != 0:
         print 'Error: Failed to modify subsystem list of feature "%s" (%d, %s)' % (name, result.status, result.txt)


def add_param(sess, store, name):
   print 'Adding parameter "%s"' % name
   result = store.AddParam(name)
   if result.status != 0:
      print 'Error: Failed to add parameter "%s" (%d, %s)' % (name, result.status, result.txt)
      return(None)
   else:
      obj = sess.getObjects(_objectId=result.outArgs['obj'])
      if obj != []:
         return(obj[0])
      else:
         return(None)


def modify_param(obj, name, action):
   # Get the specifics of the parameter
   answer = 'y'
   print 'Modifying parameter "%s"' % name
   if action == 'edit':
      answer = raw_input('Modify the type for parameter "%s" [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetType()
         if result.status != 0:
            print 'Error: Failed to retrieve type for parameter "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            val = result.outArgs['type']
            print 'Current type: %s' % val
   if answer.lower() == 'y':
      value = raw_input('Type: ')
      result = obj.SetType(value)
      if result.status != 0:
         print 'Error: Failed to modify type of parameter "%s" (%d, %s)' % (name, result.status, result.txt)
   
   if action == 'edit':
      answer = raw_input('Modify the default value for parameter "%s" [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetDefault()
         if result.status != 0:
            print 'Error: Failed to retrieve default value for parameter "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            val = result.outArgs['default']
            print 'Current default value: %s' % val
   if answer.lower() == 'y':
      value = raw_input('Default Value: ')
      result = obj.SetDefault(value)
      if result.status != 0:
         print 'Error: Failed to modify default value of parameter "%s" (%d, %s)' % (name, result.status, result.txt)

   if action == 'edit':
      answer = raw_input('Modify the description for parameter "%s" [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetDescription()
         if result.status != 0:
            print 'Error: Failed to retrieve description for parameter "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            val = result.outArgs['description']
            print 'Current description: %s' % val
   if answer.lower() == 'y':
      value = raw_input('Description: ')
      result = obj.SetDescription(value)
      if result.status != 0:
         print 'Error: Failed to modify description of "%s" for parameter "%s" (%d, %s)' % (value, name, result.status, result.txt)

   if action == 'edit':
      answer = raw_input('Modify the DefaultMustChange for parameter "%s" [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetDefaultMustChange()
         if result.status != 0:
            print 'Error: Failed to retrieve DefaultMustChange for parameter "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            val = result.outArgs['mustChange']
            print 'Current DefaultMustChange: %s' % val
   if answer.lower() == 'y':
      value = raw_input('Should this parameter require customization when used [Y/n]? ')
      if value.lower() == 'n':
         result = obj.SetDefaultMustChange(False)
      else:
         result = obj.SetDefaultMustChange(True)
      if result.status != 0:
         print 'Error: Failed to modify DefaultMustChange of parameter "%s" (%d, %s)' % (name, result.status, result.txt)

   if action == 'edit':
      answer = raw_input('Modify the expert level for parameter "%s" [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetVisibilityLevel()
         if result.status != 0:
            print 'Error: Failed to retrieve expert level for parameter "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            val = result.outArgs['level']
            print 'Current expert level: %s' % val
   if answer.lower() == 'y':
      value = raw_input('Expert level [0]: ')
      if value == '':
         value = 0
      result = obj.SetVisibilityLevel(value)
      if result.status != 0:
         print 'Error: Failed to modify expert level of parameter "%s" (%d, %s)' % (name, result.status, result.txt)

   if action == 'edit':
      answer = raw_input('Modify whether changes to parameter "%s" forces a restart [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetRequiresRestart()
         if result.status != 0:
            print 'Error: Failed to retrieve requires restart for parameter "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            val = result.outArgs['needsRestart']
            print 'Current requires restart: %s' % val
   if answer.lower() == 'y':
      value = raw_input('Restart condor when this parameter is changed [y/N]? ')
      if value.lower() == 'y':
         result = obj.SetRequiresRestart(True)
      else:
         result = obj.SetRequiresRestart(False)
      if result.status != 0:
         print 'Error: Failed to modify RequiresRestart of parameter "%s" (%d, %s)' % (name, result.status, result.txt)

   if action == 'edit':
      answer = raw_input('Modify parameter dependencies for parameter "%s" [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetDepends()
         if result.status != 0:
            print 'Error: Failed to retrieve parameter dependencies for parameter "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            print 'Current parameter dependencies:'
            val = result.outArgs['depends']
            list = ''
            for key in val.keys():
               list += '%s,' % key
            print list[:-1]
   if answer.lower() == 'y':
      value = raw_input('Comma separated list of parameter names that "%s" depends on: ' % name)
      list = process_comma_sep_list(value)
      result = obj.ModifyDepends('replace', list, {})
      if result.status != 0:
         print 'Error: Failed to modify depenecies of parameter "%s" (%d, %s)' % (name, result.status, result.txt)

   if action == 'edit':
      answer = raw_input('Modify parameter conflicts for parameter "%s" [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetConflicts()
         if result.status != 0:
            print 'Error: Failed to retrieve parameter conflicts for parameter "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            print 'Current parameter conflicts:'
            val = result.outArgs['conflicts']
            list = ''
            for key in val.keys():
               list += '%s,' % key
            print list[:-1]
   if answer.lower() == 'y':
      value = raw_input('Comma separated list of parameter names that "%s" conflicts with: ' % name)
      list = process_comma_sep_list(value)
      result = obj.ModifyConflicts('replace', list, {})
      if result.status != 0:
         print 'Error: Failed to modify conflicts of parameter "%s" (%d, %s)' % (name, result.status, result.txt)


def add_group(sess, store, name):
   print 'Adding Group "%s"' % name

   result = store.AddExplicitGroup(name)
   if result.status != 0:
      print 'Error: Failed to add group "%s" (%d, %s)' % (name, result.status, result.txt)
      return(None)
   else:
      obj = sess.getObjects(_objectId=result.outArgs['obj'])
      if obj != []:
         return(obj[0])
      else:
         return(None)


def modify_group(obj, name, action):
   print 'Modifying group "%s"' % name
   answer = 'y'
   if action == 'edit':
      answer = raw_input('Modify the node membership of group "%s" [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetMembership()
         if result.status != 0:
            print 'Error: Failed to retrieve current node membership for group "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            print 'Current node membership:'
            val = result.outArgs['nodes']
            pre_edit_list = ''
            for key in val.keys():
               pre_edit_list += '%s,' % key
            pre_edit_list = pre_edit_list[:-1]
            print pre_edit_list
   if answer.lower() == 'y':
      input = raw_input('Names of nodes included in this group (comma separated): ')
      definition = process_comma_sep_list(input)
      for node in definition.keys():
         node = node.strip()
         if node not in pre_edit_list.split(','):
            obj = get_node(session, config_store, node)
            if obj != None:
               node_obj = obj
               result = node_obj.ModifyMemberships('add', {name:True}, {})
               if result.status != 0:
                  print 'Error: Failed to add node "%s" to group "%s" (%d, %s)' % (node, name, result.status, result.txt)

      for node in pre_edit_list.split(','):
         node = node.strip()
         if node not in definition.keys():
            obj = get_node(session, config_store, node)
            if obj != None:
               node_obj = obj
               result = node_obj.ModifyMemberships('remove', {name:True}, {})
               if result.status != 0:
                  print 'Error: Failed to remove node "%s" to group "%s" (%d, %s)' % (node, name, result.status, result.txt)


def add_node(sess, store, name):
   print 'Adding Node "%s"' % name

   result = store.AddNode(name)
   if result.status != 0:
      print 'Error: Failed to add node "%s" (%d, %s)' % (name, result.status, result.txt)
      return(None)
   else:
      obj = sess.getObjects(_objectId=result.outArgs['obj'])
      if obj != []:
         return(obj[0])
      else:
         return(None)


def modify_node(obj, name, action):
   # Get the specifics of the node
   answer = 'y'
   print 'Modifying node "%s"' % name
   if action == 'edit':
      answer = raw_input('Modify the pool node "%s" belongs to [y/N]? ' % name)
      if answer.lower() == 'y':
         result = obj.GetPool()
         if result.status != 0:
            print 'Error: Failed to retrieve the pool for node "%s" (%d, %s)' % (name, result.status, result.txt)
         else:
            val = result.outArgs['pool']
            print 'Current pool: %s' % val
   if answer.lower() == 'y':
      value = raw_input('Pool: ')
      result = obj.SetPool(value)
      if result.status != 0:
         print 'Error: Failed to set pool for node "%s" to "%s" (%d, %s)' % (name, value, result.status, result.txt)


def add_subsys(sess, store, name):
   print 'Adding subsystem "%s"' % name
   result = store.AddSubsys(name)
   if result.status != 0:
      print 'Error: Failed to add subsystem "%s" (%d, %s)' % (name, result.status, result.txt)
      return(None)
   else:
      obj = sess.getObjects(_objectId=result.outArgs['obj'])
      if obj != []:
         return(obj[0])
      else:
         return(None)


def modify_subsys(obj, name, action):
   # Get the specifics of the subsystem
   answer = 'y'
   print 'Modifying subsystem "%s"' % name


def main(argv=None):
   if argv is None:
      argv = sys.argv

   broker_ip = ''
   port = '5672'
   action = ''
   features = ''
   groups = ''
   nodes = ''
   params = ''
   subsys = ''
   config_store = []
   feat_list = {}
   param_list = {}
   group_list = {}
   node_list = {}
   subsys_list = {}

   # Set signal handlers
   signal.signal(signal.SIGINT, exit_signal_handler)
   signal.signal(signal.SIGTERM, exit_signal_handler)

   long_opts = ['add', 'broker=', 'delete', 'edit', 'features=', 'groups=',
                'help', 'list', 'nodes=', 'params=', 'port=', 'subsys=']
   try:
      opts, args = getopt.getopt(argv[1:], 'ab:def:g:hln:p:o:s:', long_opts)
   except getopt.GetoptError, error:
      print str(error)
      return(1)

   for option, arg in opts:
      if option in ('-a', '--add'):
         if action != '':
            print 'Only 1 action may be specified'
            return(1)
         action = 'add'
      if option in ('-b', '--broker'):
         broker_ip = arg
      if option in ('-d', '--delete'):
         if action != '':
            print 'Only 1 action may be specified'
            return(1)
         action = 'delete'
      if option in ('-e', '--edit'):
         if action != '':
            print 'Only 1 action may be specified'
            return(1)
         action = 'edit'
      if option in ('-f', '--features'):
         features = arg
      if option in ('-g', '--groups'):
         groups = arg
      if option in ('-h', '--help'):
         print_help(argv[0])
         return(0)
      if option in ('-l', '--list'):
         if action != '':
            print 'Only 1 action may be specified'
            return(1)
         action = 'list'
      if option in ('-n', '--nodes'):
         nodes = arg
      if option in ('-p', '--params'):
         params = arg
      if option in ('-o', '--port'):
         port = arg
      if option in ('-s', '--subsys'):
         subsys = arg

   if broker_ip == '':
      print 'No broker specified.  Exiting'
      print_help(argv[0])
      return(0)

   session = Session()
   try:
      broker = session.addBroker('amqp://%s:%s' % (broker_ip, port))
   except:
      print 'Unable to connect to broker "%s"' % broker_ip
      return(1)

   # Retreive the config store object
   config_store = session.getObjects(_class='Store', _package='mrg.grid.config')
   if config_store == []:
      print 'Unable to contact Configuration Store'
   else:
      config_store = config_store[0]

   if config_store == []:
      return(1)

   # If the list action is given without features or parameters, then list
   # the details of all features and parameters in the store
   if action == 'list' and features == '' and params == '' and \
      nodes == '' and groups == '' and subsys == '':
      # List all nodes
      store_nodes = []
      store_nodes = session.getObjects(_class='Node', _package='mrg.grid.config')
      if store_nodes == []:
         print '\nThere are no nodes configured in the store'
      else:
         print '\nNodes configured in the store:'
         for node in store_nodes:
            name = node.getIndex()
            list_node_info(session, config_store, name)
            print ''

      # List all groups
      store_groups = []
      store_groups = session.getObjects(_class='Group', _package='mrg.grid.config')
      if store_groups == []:
         print '\nThere are no groups configured in the store'
      else:
         print '\nGroups configured in the store'
         for group in store_groups:
            id = group.getIndex()
            result = group.GetName()
            if result.status != 0:
               print 'Error: Unable to retrieve group name for group id "%s"\n' % id
            else:
               name = result.outArgs['name']
               list_group_info(session, config_store, name)
               print ''

      # List all parameters
      store_params = []
      store_params = session.getObjects(_class='Parameter', _package='mrg.grid.config')
      if store_params == []:
         print '\nThere are no parameters configured in the store'
      else:
         print '\nParameters configured in the store'
         for param in store_params:
            id = param.getIndex()
            list_param_info(session, config_store, id)
            print ''

      # List all features
      store_feats = []
      store_feats = session.getObjects(_class='Feature', _package='mrg.grid.config')
      if store_feats == []:
         print '\nThere are no features configured in the store'
      else:
         print '\nFeatures configured in the store'
         for feat in store_feats:
            id = feat.getIndex()
            result = feat.GetName()
            if result.status != 0:
               print 'Error: Unable to retrieve feature name for feature id "%s"' % id
            else:
               name = result.outArgs['name']
               list_feature_info(session, config_store, name)
               print''

      # List all subsystems
      store_subsys = []
      store_subsys = session.getObjects(_class='Subsystem', _package='mrg.grid.config')
      if store_subsys == []:
         print '\nThere are no subsystems configured in the store'
      else:
         print '\nSubsystems configured in the store'
         for sub in store_subsys:
            id = sub.getIndex()
            list_subsys_info(session, config_store, id)
            print ''

      return(0)

   # First add all the params/nodes/features/etc the user entered on the
   # command line, then edit them if needed.  This is done to address any
   # potential issues with conflicts/depends/includes

   # Process the nodes
   if nodes != '':
      for node in nodes.split(','):
         if action == 'add':
            obj = add_node(session, config_store, node)
            if obj != None:
              node_list[node] = obj
         elif action == 'delete':
            result = config_store.RemoveNode(node)
            if result.status != 0:
               print 'Error: Failed to remove node "%s" (%d, %s)' % (node, result.status, result.text)
               continue
         elif action == 'list':
            list_node_info(session, config_store, node)
         elif action == 'edit':
            obj = get_node(session, config_store, node)
            if obj != None:
               node_list[node] = obj

   # Process the parameters
   if params != '':
      for param in params.split(','):
         if action == 'add':
            obj = add_param(session, config_store, param)
            if obj != None:
               param_list[param] = obj
         elif action == 'delete':
            result = config_store.RemoveParam(param)
            if result.status != 0:
               print 'Error: Failed to remove parameter "%s" (%d, %s)' % (param, result.status, result.text)
         elif action == 'list':
            list_param_info(session, config_store, param)
         elif action == 'edit':
            obj = get_param(session, config_store, param)
            if obj != None:
               param_list[param] = obj

   # Process the features
   if features != '':
      for feat in features.split(','):
         if action == 'add':
            obj = add_feature(session, config_store, feat)
            if obj != None:
               feat_list[feat] = obj
         elif action == 'delete':
            obj = get_feature(session, config_store, feat)
            if obj != None:
               id = obj.getIndex()
               result = config_store.RemoveFeature(id)
               if result.status != 0:
                  print 'Error: Failed to remove feature "%s" (%d, %s)' % (feat, result.status, result.text)
         elif action == 'list':
            list_feature_info(session, config_store, feat)
         elif action == 'edit':
            obj = get_feature(session, config_store, feat)
            if obj != None:
               feat_list[feat] = obj

   # Process the groups
   if groups != '':
      for group in groups.split(','):
         if action == 'add':
            obj = add_group(session, config_store, group)
            if obj != None:
               group_list[group] = obj
         elif action == 'delete':
            obj = get_group(session, config_store, group)
            if obj != None:
               id = obj.getIndex()
               result = config_store.RemoveGroup(id)
               if result.status != 0:
                  print 'Error: Failed to remove group "%s" (%d, %s)' % (group, result.status, result.text)
         elif action == 'list':
            list_group_info(session, config_store, group)
         elif action == 'edit':
            obj = get_group(session, config_store, group)
            if obj != None:
               group_list[group] = obj

   # Process the subsystems
   if subsys != '':
      for sub in subsys.split(','):
         if action == 'add':
            obj = add_subsys(session, config_store, sub)
            if obj != None:
               subsys_list[sub] = obj
         elif action == 'delete':
            result = config_store.RemoveSubsys(sub)
            if result.status != 0:
               print 'Error: Failed to remove subsystem "%s" (%d, %s)' % (sub, result.status, result.text)
         elif action == 'list':
            list_subsys_info(session, config_store, sub)
         elif action == 'edit':
            obj = get_subsys(session, config_store, sub)
            if obj != None:
               subsys_list[sub] = obj

   # Now modify the params/features/etc

   # Modify the parameters, if needed
   for param in param_list.keys():
      modify_param(param_list[param], param, action)

   # Modify the features, if needed
   for feat in feat_list.keys():
      modify_feature(feat_list[feat], feat, action)

   # Modify the nodes, if needed
   for node in node_list.keys():
      modify_node(node_list[node], node, action)

   # Modify the groups, if needed
   for group in group_list.keys():
      modify_group(group_list[group], group, action)

   # Modify the subsystems, if needed
   for sub in subsys_list.keys():
      modify_subsys(subsys_list[sub], sub, action)

if __name__ == '__main__':
    sys.exit(main())
